version: '3'
services:
  frontend:
    build: "./frontend-nextjs"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_GATEWAY_URL=http://nginx:8080
    depends_on:
      - nginx

  backend1:
    build: "./backend-service1"
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=backend1-db
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=backend1_db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://auth-service:3003
      - DOCUMENT_SERVICE_URL=http://document-service:3004
      - JWT_SECRET=your-secret-key-here
    depends_on:
      - backend1-db
      - auth-service
      - document-service

  auth-service:
    build: "./auth-service"
    ports:
      - "3003:3003"
      - "5557:5555"
    environment:
      - DB_HOST=auth-db
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=auth_db
      - DB_PORT=5432
      - JWT_SECRET=your-secret-key-here
      - DATABASE_URL=postgresql://admin:secret@auth-db:5432/auth_db?schema=public
      - EMAIL_USER=your-email@gmail.com
      - EMAIL_PASS=your-app-password
      - KAFKA_BROKER=kafka:9092  # Add Kafka connection
    depends_on:
      - auth-db
      - kafka

  document-service:
    build: "./document-service"
    ports:
      - "3004:3000"
      - "5556:5555"
    environment:
      - DATABASE_URL=postgresql://admin:secret@document-db:5432/document_db
      - AUTH_SERVICE_URL=http://auth-service:3003
      - JWT_SECRET=your-secret-key-here
      - KAFKA_BROKER=kafka:9092  # Add Kafka connection
    depends_on:
      - document-db
      - auth-service
      - kafka
    volumes:
      - document-uploads:/src/uploads

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - auth-service
      - document-service

  backend1-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=backend1_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - backend1-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  auth-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  document-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=document_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - document-db-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  backend1-db-data:
  auth-db-data:
  document-db-data:
  document-uploads: